### ISSUE TITLE
Multi-ancestry analysis

### ISSUE THREAD

**Issue by kruthikaiyer0990** [ghm17/LOGODetect#27]
Hi,
Thank you for creating this software. 
In the paper (https://www.nature.com/articles/s41467-021-22334-6), it was noted that LOGODetect was utilized for a single-population-cross trait analysis involving 7 neuropsychiatric traits. 
The GitHub repository also provides an example of how to execute the algorithm for a cross-population analysis for one trait with EUR and EAS populations. 
Is it possible to extend this cross-population analysis to more than two populations? 
I attempted to include additional ancestry groups; no errors were thrown, but through the output I realized the algorithm only reads in the first two summary statistics and ignores the summary stats provided for other populations

Thanks,
Kruthika

**Comment by ghm17** [comment]
Hi Kruthika, 

Thanks for using our tool! LOGODetect is designed to analyze two traits because (local or global) genetic correlation is defined over two traits. However, one can still anlayze more than two traits by doing a pairwise comparison, as we did in the paper. If a region is identified in multiple trait-pair analysis, then we can say that region is genetically associated with the traits involved in the trait-pairs. Hope this helps!

Best,
Hanmin

**Comment by ghm17** [comment]
Hi Kruthika,

LOGODetect currently can analyze one trait between 2 populations on each run. For analysis across more than 2 populations, say 4 in your case, you can supply 2 of 4 populations to LOGODetect each time and do 6 population-pairs in a parallel way. We will also update the software in the future, to incorporate the function that allows more than 2 traits/populations in a single run. 

Best,
Hanmin
